services:
  - type: web
    name: employee-performance-analysis
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard_app.py --server.port=$PORT --server.address=0.0.0.0
    runtime: python
    region: oregon
    plan: free
    autoDeploy: true
